# Define a versão do blueprint do Render
version: 1

# Lista de serviços a serem implantados
services:
  # 1. Serviço do Root Config
  - type: web
    name: bytebank-root
    plan: free
    runtime: docker
    dockerfilePath: ./bytebank-root/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://fiap-grupo-15-bytebank-backend-9f339827bd67.herokuapp.com

  # 2. Serviço do MFE Homepage
  - type: web
    name: bytebank-homepage
    plan: free
    runtime: docker
    dockerfilePath: ./mfe-homepage/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://fiap-grupo-15-bytebank-backend-9f339827bd67.herokuapp.com

  # 3. Serviço do MFE Dashboard
  - type: web
    name: bytebank-dashboard
    plan: free
    runtime: docker
    dockerfilePath: ./mfe-dashboard/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://fiap-grupo-15-bytebank-backend-9f339827bd67.herokuapp.com

  # 4. Serviço do MFE Not Found
  - type: web
    name: bytebank-notfound
    plan: free
    runtime: docker
    dockerfilePath: ./mfe-notfound/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://fiap-grupo-15-bytebank-backend-9f339827bd67.herokuapp.com